DROP VIEW IF EXISTS TestQuestionsFull;
DROP TABLE IF EXISTS TestQuestions;
DROP TABLE IF EXISTS Sessions;
DROP TABLE IF EXISTS TestsResults;
DROP TABLE IF EXISTS QuestionType;
DROP TABLE IF EXISTS WelshWords;
DROP TABLE IF EXISTS Users;